apiVersion: apps/v1
king: Deployment
metadata:
	name: name-deploy
	labels:
		app: nginx
spec:
	replicas: 2
	selector : 
		matchLabels:
			app: nginx
	template:
		metadata:
			labels:
			app: niginx
		spec:
			containers:
			- name: nginx
			  image: nginx:1.16
			  ports:
			  - containerPort:8080
			  
---
apiVersion: v1
king: Service
metadata:
	name: name-service	
spec:	
	selector :		
		app: nginx
	ports:
		- protocol:TCP
		  port: 80
		  targetPort: 8080
