apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx01
  name: nodeportsvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx01
  type: NodePort
