#Deploy the manifest below and all pods will go for pending. Assign any of the POD a label as perf=high as shown below.
#Then all PODs will start and endup in same host. This is POD Affinity

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      cloud: aws
  replicas: 3
  template:
    metadata:
      labels:
        cloud: aws
        performance: high
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: perf
                operator: In
                values:
                - high
            topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: web-app
        image: nginx:1.16-alpine